services:
  app:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
  nginx:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app